spring:
  application:
    name: notification-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms

# Server Configuration
server:
  port: ${SERVER_PORT:8082}

# Logging Configuration
logging:
  level:
    com.enterprise.notification: INFO
